.flake8, .isort.cfg, .pre-commit-config.yaml
=> Add pre-commit hook for dev

.pre-commit-config.yaml
- quiet black
- quiet hooks/post_gen
- last tweak
- last tweak
=> quiet black

{{ cookiecutter.repo_name }}/src/{{ cookiecutter.package_dir_name }}/tests/conftest.py, {{ cookiecutter.repo_name }}/src/{{ cookiecutter.package_dir_name }}/tests/debug.py
=> Fix header on debug.py and add conftest.py

{{ cookiecutter.repo_name }}/doc/Makefile
=> Change makefile

{{ cookiecutter.repo_name }}/src/{{ cookiecutter.package_dir_name }}/tests/run.py
=> Add test / run.py

{{ cookiecutter.repo_name }}/.gitignore
=> Add to gitignore

{{ cookiecutter.repo_name }}/.gitignore
=> fix gitignore

cookiecutter.json, test_utils.py, {{ cookiecutter.repo_name }}/pyproject.toml
Closes #7
Adds a max supported version question, like the min version question.
git diff output:
=> Max version question

{{ cookiecutter.repo_name }}/CHANGELOG.rst
=> Add changelog.rst

{{ cookiecutter.repo_name }}/CODE_OF_CONDUCT.rst
Do we need this? I mentioned it in readme
=> Add code of conduct

{{ cookiecutter.repo_name }}/README.rst
Fix #12 
How it [looks like](https://github.com/Tieqiong/readme/tree/0296420fdd0f22d43d8545e1d2adf275b83e4e8e) after cookiecut
Need discussion and changes:
- project icon
-- Higher resolution
-- Make it the GitHub org avatar?
- Badges
-- DOI
-- Test
- Contributor.rst in diffpy.utils?
=> Add Readme

cookiecutter.json, {{ cookiecutter.repo_name }}/doc/Makefile, {{ cookiecutter.repo_name }}/doc/source/conf.py, {{ cookiecutter.repo_name }}/pyproject.toml, {{ cookiecutter.repo_name }}/src/{{ cookiecutter.package_dir_name }}/__init__.py, {{ cookiecutter.repo_name }}/src/{{ cookiecutter.package_dir_name }}/tests/run.py, {{ cookiecutter.repo_name }}/src/{{ cookiecutter.package_dir_name }}/version.py
Change `{{ cookiecutter.project_name }}` to `{{ cookiecutter.repo_name }}` and `{{cookiecutter.package_dist_name }}`
=> Change cookiecutter refer name

{{ cookiecutter.repo_name }}/.github/workflows/main.yml
=> Add lines in yaml file for Codecov

README.md, {{ cookiecutter.repo_name }}/MANIFEST.in
Closes https://github.com/Billingegroup/cookiecutter/issues/108
=> Update MANIFEST.in to include tests, src, and requirements files

README.md
For our background information.
=> Add info pull request vs. pull request target in GitHub CI

{{ cookiecutter.repo_name }}/.github/workflows/matrix-and-codecov-on-merge-to-main.yml, {{ cookiecutter.repo_name }}/README.rst
=> Update GitHub CI link for matrix-codecov update

README.md
Closes https://github.com/Billingegroup/cookiecutter/issues/143
Improving the instructions based on today's real-time session.
=> Improve cookiecutter workflow documentation 

{{ cookiecutter.repo_name }}/README.rst
=> Remove mention of installing pip dependencies

hooks/post_gen_project.py
=> Remove boost-specific items in setup.py

README.md, cookiecutter.json, hooks/post_gen_project.py
=> change prompt booster and headless

{{ cookiecutter.repo_name }}/.github/ISSUE_TEMPLATE/bug_feature.md, {{ cookiecutter.repo_name }}/.github/ISSUE_TEMPLATE/release_checklist.md, {{ cookiecutter.repo_name }}/README.rst
- **Add bug, feature, and release issues**
- **Add install check after conda install, add getting started**
=> Add installation check in readme, remove python=3 conda install in readme

cookiecutter.json, {{ cookiecutter.repo_name }}/pyproject.toml
Closes https://github.com/Billingegroup/cookiecutter/issues/116
=> Update requires-python, set min py311, max py313

{{ cookiecutter.repo_name }}/.github/ISSUE_TEMPLATE/release_checklist.md
=> Add post-release checklist for GitHub release issues template

.github /ISSUE_TEMPLATE/bug_feature.md
Just like other packages, helping us communicate the problem and provide a potential solution
=> Add standard bug_feature GitHub issue template

{{ cookiecutter.repo_name }}/.github/ISSUE_TEMPLATE/release_checklist.md
As discussed via Slack, we want to have a checklist for 1) new dependencies added in `meta.yml` 2) issues are addressed in the feedstock.
=> Add conda-forge checklist for new dependencies and resolve issues

.github/workflows/check-news-item.yml, .pre-commit-config.yaml, LICENSE.rst, README.md, cookiecutter.json, doc/source/cookiecutter_guide.rst, news/prettier.rst, {{ cookiecutter.repo_name }}/.codecov.yml, {{ cookiecutter.repo_name }}/.github/ISSUE_TEMPLATE/release_checklist.md, {{ cookiecutter.repo_name }}/.pre-commit-config.yaml, {{ cookiecutter.repo_name }}/README.rst, {{ cookiecutter.repo_name }}/doc/source/conf.py, {{ cookiecutter.repo_name }}/doc/source/license.rst, {{ cookiecutter.repo_name }}/environment.yml
No manual modifications have been done.
=> Add `prettier` to pre-commit hook for automatic linting of `.md`, `.rst`, .`yml`

environment.yml, news/add-py-env.rst, requirements/docs.txt
We should be able to render docs online via workflow dispatch.
=> Add `environment.yml` and requirement .txt files to use Billinge group's reusable CI workflows

doc/source/index.rst, news/statement-of-need.rst, pyproject.toml
Closes #205 - write compelling statements/descriptions:
I spent about an hour... maybe we could further refine these statements when we further review the doc fully later
=> Add motivating statement and full description for bg-cookiecutter

cookiecutter.json, doc/source/conf.py, doc/source/frequently_asked_questions.rst, news/doc-python-version.rst
=> feat: Configure default Python min/max version in documentation

doc/source/conda-forge-guide.rst, doc/source/frequently-asked-questions.rst, doc/source/getting-started.rst, doc/source/index.rst, doc/source/release-guide.rst, doc/source/scikit-package-guide.rst, news/jan-15-docs.rst
=> docs: Fix minor typos and fix link in index.rst to scikit-package-guide.rst

doc/source/snippets/package-create-user-inputs.rst, news/clarify_instructions.rst
=> Clarify instructions in creating a new package

.github/workflows/tests-on-pr.yml, news/remove-test-on-pr.rst
Closes https://github.com/Billingegroup/scikit-package/issues/279
=> CI: remove `tests on PR` on push

news/status.rst, pyproject.toml
Closes https://github.com/Billingegroup/scikit-package/issues/291
=> chore: update dev status from 5 to 3 (alpha) in pyproject.toml

doc/source/migration-guide.rst, news/mar27-doc-typo.rst
Closes #286 
Would you be referring to this typo here? @sbillinge
=> docs: fix typo in Section 2.3 spotted by @sbillinge

news/command.rst, src/scikit_package/app.py
Closes https://github.com/Billingegroup/scikit-package/issues/301
Example:
```
(base) macbook@Macbook-Air-327 skpkg % package create public
[1/16] project_owner_name (Simon Billinge): 
...
```
=> feat: implement `package create workspace, system, public` commands

news/conda-forge-command.rst, src/scikit_package/app.py
Support ``package create conda-forge`
Closes https://github.com/Billingegroup/scikit-package/issues/315
=> feat: add `package create conda-forge` command

doc/source/new-project-guide/level-3-tutorial.rst, news/202504-doc-command-example-folder-level-3.rst
Addresses https://github.com/Billingegroup/scikit-package/issues/328
=> docs: update level-3 doc folder naming convention based on feedback in manuscript

doc/source/new-project-guide/level-1-tutorial.rst, doc/source/new-project-guide/level-2-tutorial.rst, doc/source/new-project-guide/level-4-tutorial.rst, doc/source/snippets/conda-env-setup-simple.rst, news/update-level-1-2-example.rst
Closes https://github.com/Billingegroup/scikit-package/issues/328
=> doc: update example file name from `calculator.py` to `functions.py`  in Level 4-5  and `example_code.py` in Level 1 and `shared_functions` in Level 2

doc/source/new-project-guide/level-1-tutorial.rst, doc/source/new-project-guide/level-4-tutorial.rst, doc/source/snippets/conda-env-setup-simple.rst, doc/source/snippets/github-pre-commit-setup.rst, doc/source/snippets/scikit-installation.rst, news/pre-commit-conflict-instruction.rst
Addresses #311 
> Ensure conda config --channels conda-forge is provided in the installation instruction
-> Done
@yucongalicechen and @bobleesj went through the Level 4 instructions step-by-step in-person.
=> docs: incorporate level 4 tutorial feedback with Yucong and bobleesj

cookiecutter.json, hooks/post_gen_project.py, news/github-org-name.rst, {{ cookiecutter.github_repo_name }}/AUTHORS.rst, {{ cookiecutter.github_repo_name }}/README.rst, {{ cookiecutter.github_repo_name }}/doc/source/index.rst, {{ cookiecutter.github_repo_name }}/pyproject.toml, {{ cookiecutter.github_repo_name }}/src/{{ cookiecutter.package_dir_name }}/__init__.py, {{ cookiecutter.github_repo_name }}/src/{{ cookiecutter.package_dir_name }}/version.py
Closes https://github.com/Billingegroup/scikit-package/issues/360
=> refactor:  change cookiecuter user input value from `github_org` to `github_username_or_orgname.`

doc/source/new-project-guide/level-3-tutorial.rst, news/no-news-needed.rst
=> docs: instructions for setting `PYTHONPATH` i level 3

doc/source/frequently-asked-questions.rst, doc/source/new-project-guide/level-4-tutorial.rst, doc/source/new-project-guide/level-5-tutorial.rst, news/pc-death-migrate-rst.rst
Closes #303 
Closes https://github.com/Billingegroup/scikit-package/issues/354
=> docs: add instruction on how to avoid pre-commit auto-fix and convert .md to .rst

AUTHORS.rst, cookiecutter.json, doc/source/new-project-guide/level-4-tutorial.rst, hooks/post_gen_project.py, news/level-5-user-owner-input.rst, {{ cookiecutter.github_repo_name }}/README.rst, {{ cookiecutter.github_repo_name }}/pyproject.toml
=> refactor: modify `proj_owner` to `maintainer` in level 5 cookiecutter.json inputs

doc/source/frequently-asked-questions.rst, news/faq-why-readme-rst.rst
Closes https://github.com/Billingegroup/scikit-package/issues/368
I also improved sentences discussing "namespace support" (no longer using the term "namespace package")
=> docs: add reasons for adopting README.rst in Level 5

doc/source/pypi-release-guide.rst, news/seman-version.rst
Closes https://github.com/Billingegroup/scikit-package/issues/384
=> docs: adopt Semantic Versioning 2.0.0 for pre-release GitHub tag name.

doc/source/frequently-asked-questions.rst, doc/source/new-project-guide/level-4-tutorial.rst, doc/source/snippets/news-file-format.rst, news/move-manuscript-excised.rst
Closes https://github.com/Billingegroup/scikit-package/issues/385
=> docs: Add descriptions for each workflow in Level 5 in a PR

doc/source/frequently-asked-questions.rst, news/faq-replace-variables.rst
Closes https://github.com/Billingegroup/scikit-package/issues
=> add a FAQ section on which workflow files to update when there is a new stable Python version.

doc/source/conf.py, news/edit-on-gh.rst, {{ cookiecutter.github_repo_name }}/doc/source/conf.py
Closes https://github.com/Billingegroup/scikit-package/issues/392
=> docs: implement 'edit on github' feature for each page

news/gh-issue-release-template.rst, {{ cookiecutter.github_repo_name }}/.github/ISSUE_TEMPLATE/release_checklist.md
Addresses https://github.com/Billingegroup/scikit-package/pulls?q=is%3Apr+is%3Aclosed
=> chore: in GitHub release issue, don't mention specific username but replace it with 'maintainer' 

news/rm-diffpy.rst, {{ cookiecutter.github_repo_name }}/README.rst
=> style: remove diffpy hard-coded in README

doc/source/snippets/scikit-installation.rst, news/conda-channel.rst
Closes https://github.com/Billingegroup/scikit-package/issues/421
The goal is to ensure new Level 4 user sets `conda-forge`.
Rendered:
Please review the instruction.
=> docs: Add an explicit instruction to configure conda-forge channel in Level 4, 5 tutorial instructions.

doc/source/tutorials/level-1-2-3-tutorials.rst, news/level-3-init.rst
Closes #446 
Clarify the use of ``__init__.py`` in python
Screenshot:
Please review the improved sentence.
=> docs: clarify the use of __init__.py in Level 3 tutorial, brought by @sbillinge

AUTHORS.rst, doc/source/index.rst, news/tieqiong-author.rst
Add @Tieqiong to the author list - as reflected in the manuscript
=> chore: add Tieqiong Zhang to author list

doc/source/support/frequently-asked-questions.rst, doc/source/tutorials/level-5-tutorial.rst, news/config-doc.rst
Closes #461 
Please check the rendered documentation.
Optional section in the level 5 tutorial
Two detailed descriptions in FAQ/Project setup
=> doc: add instructions for overriding the default prompt values

doc/source/tutorials/tutorial-level-1-2-3.rst, doc/source/tutorials/tutorial-level-4.rst, news/simon-docclean2.rst
Sorry @bobleesj I typed into my editor but I obviously don't know how to save before exiting....
This PR is simon polishing through level 3 (and I think at the beginning of level4)
we can merge.  But for the next one, let's just leave it open as I go through, I can keep pushing.
=> doc: Simon tweaks to end of level 3

doc/source/snippets/github-create-new-repo.rst, doc/source/snippets/github-upload-readme-pre-commit.rst, doc/source/snippets/package-install-test-local.rst, doc/source/snippets/pre-commit-local-setup.rst, doc/source/snippets/user-input-level-5.rst, doc/source/tutorials/tutorial-level-4-to-5.rst, doc/source/tutorials/tutorial-level-4.rst, news/simon-4+.rst
doc polish
ready for review and merge
=> doc: Simon polishing 

.pre-commit-config.yaml, hooks/post_gen_project.py, news/pre-commit-misses.rst, {{ cookiecutter.github_repo_name }}/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, {{ cookiecutter.github_repo_name }}/tests/test_functions.py
A couple simple changes in that should address some of the pre-commit issues addressed in my recent comment (i dont want to tag it because there is more to do).
Closes #518
=> bug: `black` failures in source files

news/cf-unit-test.rst, src/scikit_package/cli/add.py, tests/test_add_news.py, tests/test_update_cf.py
Closes https://github.com/scikit-package/scikit-package/issues/532
Closes https://github.com/scikit-package/scikit-package/issues/525
I tested the core functionality of 1) updating meta.yaml for `package update conda-forge` and 2) generating `news/<branch-name>.rst` for `package add news`.
No new functionally has been added.
=> tests: write unit tests for `package update conda-forge` and `package add news`

AUTHORS.rst, doc/source/index.rst, doc/source/overview.rst, doc/source/tutorials/tutorial-level-5.rst, news/easy-getting-started.rst
Closes #545  - providing a few "Getting started" code snippets under our "Getting Started section"
Please review the content. Here is the rendered version:
=> Include introductory code snippets under the Getting Started page for first-time users.

doc/source/release-guides/conda-forge.rst, doc/source/support/frequently-asked-questions.rst, doc/source/tutorials/tutorial-level-5-migration.rst, news/doc-run-build-fix.rst
Closes https://github.com/scikit-package/scikit-package/issues/557 - improve conda-forge meta.yaml process
Closes #555  - instruct how to setup custom CLI commands for remote pytest CI
Please review the in-line comments with the rendered doc shown.
=> Add an instruction how to run extra custom CLI commands in test-on-pr and matrix CI.

README.rst, news/add-url-link-to-pr.rst, {{ cookiecutter.github_repo_name }}/README.rst
- **add target to PR**
- **news: Add target to PR welcome badge in README.rst**
=> Add target to PR welcome badge in README.rst

.github/ISSUE_TEMPLATE/release_checklist.md, docs/source/release-guides/conda-forge.rst, docs/source/snippets/package-install-test-local.rst, docs/source/support/frequently-asked-questions.rst, docs/source/tutorials/tutorial-level-4-to-5.rst, docs/source/tutorials/tutorial-level-4.rst, docs/source/tutorials/tutorial-level-5-migration.rst, news/fix-doc.rst, {{ cookiecutter.github_repo_name }}/.github/ISSUE_TEMPLATE/release_checklist.md, {{ cookiecutter.github_repo_name }}/README.rst, {{ cookiecutter.github_repo_name }}/docs/source/getting-started.rst
Closes #580 
- **chore: fix test.txt to tests.txt in doc**
- **news: Rename test.txt to tests.txt in doc**
=> Rename test.txt to tests.txt in doc

README.rst, docs/source/index.rst, news/version-cite.rst
Closes https://github.com/scikit-package/scikit-package/issues/489
- **docs: add arxiv citation to index.rst and readme**
- **news: Add ArXiv link to doc and readme**
=> Add ArXiv link to doc and readme

news/verseion-robust.rst, src/scikit_package/version.py, {{ cookiecutter.github_repo_name }}/src/{{ cookiecutter.package_dir_name }}/version.py
=> Add try-error fallback to __version__

news/fix-test-copy-all-files.rst, tests/test_io.py
Closes #590
Please check the modification.
=> fix: use simpler assertions in `test_copy_all_files_bad`.

docs/source/snippets/level-5-optional-sections.rst, news/doc-package-update.rst
Closes #615
Please see the added part in the documentation
=> doc: add instructions for `package update`
