- {{ cookiecutter.repo_name }}/requirements/README.txt
- {{ cookiecutter.repo_name }}/requirements/build.txt
- {{ cookiecutter.repo_name }}/requirements/docs.txt
- {{ cookiecutter.repo_name }}/requirements/test.txt
Closes #56. Add `pip.txt` (not present in `diffpy.utils`, but used for projects that may need installs not available on `conda`). Add a `README.txt` explaining what each file does. All other files are the same except for the following changes:
We will keep `run.txt` empty as users must decide for themselves what packages are required for their program. Though it will likely include `numpy`, it may not.
The packages `pytest-mock` and `freezegun` are for specific tests in `diffpy.utils`, we will not include them here.
> Requirements directory

- cookiecutter.json
- test_utils.py
- {{ cookiecutter.repo_name }}/pyproject.toml
Closes #66, #68 (did a quick fix for this)
The cookiecutter now prompts the user with three keyword questions, which default to blank. The following is the git diff of pyproject.toml with the diffpy.utils description. The only notable difference is single quotes vs double quotes, which is just an artifact of the cookiecutter input and probably can't be easily changed. It shouldn't matter though.
Also, a result of this is that `test_utils.py` had to be updated, so if this is merged everyone should definitely sync right away.
> Add keyword inputs

- test_utils.py
- {{ cookiecutter.repo_name }}/pyproject.toml
It seems as if the `keywords` were not tested. There was extra spacing in the keywords. 
New diff:
> Fix spacing in pyproject.toml classifiers

- {{ cookiecutter.repo_name }}/.flake8
- {{ cookiecutter.repo_name }}/AUTHORS.rst
- {{ cookiecutter.repo_name }}/LICENSE.rst
- Closes #10
Fixes link currently in `diffpy.utils` and remove `versioneer`.
- Closes #14 
License completely changed to base BSD 3-Clause License.
- Closes #30
Rename `AUTHORS.txt` to `AUTHORS.rst` and change contribution blurb.
> Add root files

- {{ cookiecutter.repo_name }}/news/TEMPLATE.rst
Closes #80 by adding news directory and TEMPLATE.rst file in cookiecutter.
> Create news directory and TEMPLATE.rst in cookiecutter

- test_utils.py
- {{ cookiecutter.repo_name }}/doc/source/api/{{ cookiecutter.package_dir_name }}.example_package.rst
- {{ cookiecutter.repo_name }}/doc/source/api/{{ cookiecutter.package_dir_name }}.rst
- {{ cookiecutter.repo_name }}/doc/source/index.rst
- {{ cookiecutter.repo_name }}/doc/source/release.rst
Closes #63 
Added `release.rst` that copies the `CHANGELOG.rst` in root.
Change project short description in our test.
This image above assumes our `README.rst` has an `installation` section. If we do not want to mandate that, I will just link to the repo.
> Index for documentation

- {{ cookiecutter.repo_name }}/pyproject.toml
Closes https://github.com/Billingegroup/cookiecutter/issues/110
This change allows pip users to download all dependencies associated with the package.
@Tieqiong 
Similar PRs made to individual cookiecuttered packages:
- https://github.com/diffpy/diffpy.structure/pull/98
- https://github.com/Billingegroup/bg-mpl-stylesheets/pull/60
> Add dynamic dependency in pyproject.toml

- {{ cookiecutter.repo_name }}/.github/workflows/check-news-item.yml
- {{ cookiecutter.repo_name }}/.github/workflows/check-news.py
Closes https://github.com/Billingegroup/cookiecutter/issues/95
CI fails when no news item is provided with the following warning:
> add a workflow that checks for a news

- {{ cookiecutter.repo_name }}/pyproject.toml
v2.0.0 is now available - https://setuptools-git-versioning.readthedocs.io/en/stable/install.html
Should be merged after https://github.com/conda-forge/diffpy.structure-feedstock/pull/17 is merged and tested where `setuptools-git-versioning >= 2.0` is used.
> Update setuptools-git-versioning >= 2.0

- {{ cookiecutter.repo_name }}/README.rst
Tested locally:
For `bg-mpl-stylesheets`:
```
To confirm that the installation was successful, type ::
python -c "import bg_mpl_stylesheets; print(bg_mpl_stylesheets.__version__)"
```
For `diffpy.snmf`: 
```
To confirm that the installation was successful, type ::
python -c "import diffpy.snmf; print(diffpy.snmf.__version__)"
```
> Use package dir name for install check in readme

- {{ cookiecutter.repo_name }}/.github/ISSUE_TEMPLATE/release_checklist.md
Closes #179 - update release checklist based on `pdffit2`, `fourigui` deployment experience
> Improvement release instructions based on pdffit2 and fourgui - separate instructions for PyPI rc, full release, conda forge

- doc/source/cookiecutter_guide.rst
- doc/source/frequently_asked_questions.rst
- doc/source/getting_started.rst
- doc/source/index.rst
- doc/source/release_guide.rst
- news/getting-started.rst
- Added potential benefits and features (both non-technical and technical)
- Categorize into two groups 1) here for cookiecut 2) here for release
> Add Getting Started section and description of bg-cookiecutter in index.rst

- .flake8
- .isort.cfg
- environment.yml
- news/line-length.rst
- pyproject.toml
- {{ cookiecutter.github_repo_name }}/.flake8
- {{ cookiecutter.github_repo_name }}/.isort.cfg
- {{ cookiecutter.github_repo_name }}/pyproject.toml
> feat: Change default line-length to 79 characters in `black`, `flake`, and `isort` configuration files for PEP8 compatibility.

- hooks/post_gen_project.py
- news/remove-empty.rst
Here, just remove one empty blank line that is later processed by pre-commit automatically as shown below:
> chore: remove an extra blank in e.g., `src/diffpy/__init__.py`

- CHANGELOG.rst
- doc/source/new-project-guide.rst
- news/feb25-doc.rst
Some of immediate fixes in the docs. Will merge it since we will do an overall review later.
> docs: fix typo in how to start guide

- {{ cookiecutter.github_repo_name }}/README.rst
Having this makes everyone that creates their own package a professor.
> style: remove `prof.` from readme

- hooks/post_gen_project.py
- news/lowercap.rst
Closes https://github.com/Billingegroup/scikit-package/issues/283
When the user enters `diffpy.SAF`, the directory name under `src` becomes `saf` instead of `SAF`
> fix: lowercase package directory name under src directory for namespace package

- news/package-create-refactor.rst
- src/scikit_package/app.py
Closes https://github.com/Billingegroup/scikit-package/issues/307
Setup global variable of `SKPKG_GITHUB_URL = "https://github.com/Billingegroup/scikit-package"` at the top of the file, suggested by @sbillinge
> refactor: use global variable for skpkg github URL in app.py

- news/better-tests.rst
- {{ cookiecutter.github_repo_name }}/src/{{ cookiecutter.package_dir_name }}/calculator.py
- {{ cookiecutter.github_repo_name }}/tests/test_calculator.py
Closes https://github.com/Billingegroup/scikit-package/issues/308
Added docstrings for the `dot_product` function. I have noticed that this function not only work with multiple array sizes, but also various `array_like` types. Hence, added a few more test cases.
> docs: implement docstrings to `dot_product` fuction using group's standards.

- doc/source/frequently-asked-questions.rst
- doc/source/new-project-guide/level-5-tutorial.rst
- news/news-permission-workflow-instruction.rst
> docs: add tutorial on GitHub Actions to run `news-check` CI

- hooks/post_gen_project.py
- news/remove-namespace-extra.rst
Closes #349 
Tested in `labpdfproc`: https://github.com/diffpy/diffpy.labpdfproc/pull/176#issuecomment-2836057100
> refactor: remove the import of `extend_path` from `pkgutil` in `diffpy/__init__.py`

- doc/source/frequently-asked-questions.rst
- news/pre-commit-figure.rst
Closes https://github.com/Billingegroup/scikit-package/issues/374 
This is the rendered LATEX version in our manuscript (under SI):
> docs:  Add a figure on `pre-commit` local and remote setup across Level 3 to 5 under FAQ.

- cookiecutter.json
- doc/source/conda-forge-release-guide.rst
- doc/source/frequently-asked-questions.rst
- doc/source/migration-guide.rst
- doc/source/new-project-guide/level-4-tutorial.rst
- doc/source/new-project-guide/level-5-tutorial.rst
- doc/source/pypi-release-guide.rst
- doc/source/snippets/github-codecov-setup.rst
- news/owner-maintainer-doc.rst
- {{ cookiecutter.github_repo_name }}/pyproject.toml
Addresses https://github.com/Billingegroup/scikit-package/issues/372 (rename owner to maintainter)
Closes https://github.com/Billingegroup/scikit-package/issues/362
Also, fixed the following from (can't wrap words outside of the page)
to
> docs: define clear roles for "owner" and "maintainer" in the documentation

- hooks/post_gen_project.py
- news/workflow-dynamic.rst
This change is required to dynamically populate the workflow template files in our release-scripts.
@sbillinge ready to be merged.
> refactor: update `GITHUB_ADMIN_USERNAME` to `MAINTAINER_GITHUB_USERNAME` in host gen hook

- doc/source/examples.rst
- doc/source/index.rst
- doc/source/overview.rst
- doc/source/release-guides/pypi-github.rst
- doc/source/snippets/scikit-installation.rst
- doc/source/tutorials/level-1-2-3-tutorials.rst
- doc/source/tutorials/level-5-tutorial.rst
- news/doc-check-links.rst
- {{ cookiecutter.github_repo_name }}/doc/source/getting-started.rst
Closes https://github.com/Billingegroup/scikit-package/issues/402
Also I've adopted some "nice looking" buttons using `:ref:guilabel` for button items that would separate from `variable names` as shown below:
> docs: fix image relative URLs, use guilabel for clickable buttons in instructions

- .github/ pull_request_template.md
- news/pr-template.rst
- {{ cookiecutter.github_repo_name }}/.github/ pull_request_template.md
Closes #414 - I proposed the following PR template below:
I have also adopted the above format in this current PR.
@sbillinge Please review the content.
> style: add PR template to save maintainer's time and guide contributors to make docs

- doc/source/index.rst
- doc/source/programming-guides/billinge-group-standards.rst
- doc/source/release-guides/conda-forge.rst
- doc/source/release-guides/pypi-github.rst
- doc/source/snippets/doc-pr-preview.rst
- doc/source/snippets/news-file-format.rst
- doc/source/snippets/scikit-installation.rst
- doc/source/support/frequently-asked-questions.rst
- doc/source/tutorials/level-5-tutorial.rst
- news/favicon-faq.rst
Closes https://github.com/Billingegroup/scikit-package/issues/424
- Teaching how to set logo/favicon.
- Fixed doc building errors as shown below:
Please see my in-line comments for reasons and review.
> docs: add favicon/logo instruction in the doc, resolve all doc building errors

- CHANGELOG.rst
- doc/source/snippets/news-file-format.rst
- news/news-backquote.rst
Closes https://github.com/Billingegroup/scikit-package/issues/423
Adopt `.rst` style backquotes for news items since we are using `.rst` files.
Please see the new quick instruction.
> docs: encourage using .rst backquotes instead of .md style

- doc/source/snippets/github-ci-permission.rst
- doc/source/support/frequently-asked-questions.rst
- doc/source/tutorials/level-5-tutorial.rst
- news/allow-workflow-to-run.rst
A while ago @sbillinge mentioned the CI problem while standardizing `bglk-euxfel` in https://github.com/Billingegroup/scikit-package/issues/292 and @bobleesj fixed the problem in the PR attached  in https://github.com/Billingegroup/scikit-package/pull/342.
It was provide din the tutorial, but also providing error msg and solution in the FAQ section as well.
> docs: add how to solve GitHub permission CI error encountered with news GitHub CI under FAQ

- doc/source/conf.py
- doc/source/snippets/doc-pr-preview.rst
- news/doc-preview-org-tutorial.rst
- {{ cookiecutter.github_repo_name }}/.readthedocs.yaml
- {{ cookiecutter.github_repo_name }}/doc/source/conf.py
Closes https://github.com/Billingegroup/scikit-package/issues/418
Links: 
- Step 1. https://app.readthedocs.org
- Step 3.1 https://github.com/settings/applications
- Steep 4. https://app.readthedocs.org/dashboard/import/
> docs: add tutorial on how to add GitHub org to use Read the Doc  and configure `.readthedocs.yaml` within the template folder

- .github/workflows/build-wheel-release-upload.yml
- .github/workflows/check-news-item.yml
- .github/workflows/matrix-and-codecov-on-merge-to-main.yml
- .github/workflows/publish-docs-on-release.yml
- .github/workflows/tests-on-pr.yml
- README.rst
- doc/source/conf.py
- doc/source/examples/migration.rst
- doc/source/index.rst
- doc/source/programming-guides/billinge-group-standards.rst
- doc/source/snippets/news-file-format.rst
- doc/source/support/frequently-asked-questions.rst
- doc/source/tutorials/level-5-tutorial.rst
- hooks/post_gen_project.py
- news/url-skpkg.rst
- pyproject.toml
- src/scikit_package/__init__.py
- src/scikit_package/app.py
- src/scikit_package/version.py
- {{ cookiecutter.github_repo_name }}/README.rst
- {{ cookiecutter.github_repo_name }}/doc/source/index.rst
Closes https://github.com/scikit-package/scikit-package/issues/433
We recently transfer repos from `Billingegroup` to `scikit-package`. So this PR updates URLs in the doc and variables.
Please review the new URLs and merge the code.
> refactor: update URL links from `Billingegroup/repo` to `scikit-package/repo`

- doc/source/release-guides/pypi-github.rst
- doc/source/tutorials/level-5-tutorial.rst
- news/vulture-in-doc.rst
closes #435 
Added a brief option to run `vulture` in the documentation for Level 5 and PyPI release as discussed here https://github.com/scikit-package/scikit-package/issues/434#issuecomment-2876955945.
> docs: add instructions for using `vulture` in Level 5 and PyPI release instructions

- doc/source/conf.py
- doc/source/index.rst
- news/tag-pr-preview.rst
- {{ cookiecutter.github_repo_name }}/doc/source/conf.py
- {{ cookiecutter.github_repo_name }}/doc/source/index.rst
Closes https://github.com/scikit-package/scikit-package/issues/440
Instead of giving the following error msg:
The new error msg is `"No version found. The correct version will appear in the released version."
Please review the change in the warning msg as recommended and merge.
> refactor: indicate correct version will appear in doc PR preview error message

- doc/source/release-guides/pypi-github.rst
- doc/source/snippets/codespell-ignore.rst
- doc/source/support/frequently-asked-questions.rst
- doc/source/tutorials/level-5-tutorial.rst
- news/ruleset-config-faq.rst
- {{ cookiecutter.github_repo_name }}/CODE_OF_CONDUCT.rst
Closes https://github.com/scikit-package/scikit-package/issues/443
This PR address the questions of "what happens when release CI fail" after creating and pushing the tag to the remote.
Please read the content. Please also check my in-line comments.
> docs: provide instructions what to do when release CI fails

- README.rst
- doc/source/programming-guides/billinge-group-standards.rst
- news/naming-convention.rst
- {{ cookiecutter.github_repo_name }}/README.rst
Closes https://github.com/scikit-package/scikit-package/issues/444
This PR is used to indicate when not to apply the `-` or `_` naming convention:
Please provide feedback on the instruction if it needs to be modified.
> docs: provide an instruction when not to follow the file/folder naming convention for configuration files.

- news/config.rst
- src/scikit_package/app.py
Closes #375 
Use the following checklist items when applicable (select only what applies):
`cookiecutter`  provides a way to set the default configs through "-- config-file" option in  https://cookiecutter.readthedocs.io/en/latest/advanced/user_config.html.This. This implementation utilized this option. 
(1) Ethan wants better default values. He create `~/.skpgrc`
```yaml
{
"default_context":
{
"project_name": a-new-project-package",
"github_username_or_orgname": "billingegroup",
"github_repo_name": "{{ cookiecutter.project_name|replace(' ', '-')|lower }}",
"conda_pypi_package_dist_name": "{{ cookiecutter.project_name|replace(' ', '-')|lower }}",
"package_dir_name": "{{ cookiecutter.project_name|replace(' ', '_')|replace('-', '_')|lower }}",
"contributors": "Sangjoon Lee, Simon Billinge", …
```
> feat: Allow users to set default configurations.

- doc/source/support/frequently-asked-questions.rst
- news/level-3-init.rst
- news/sphinx-api-fix.rst
We want users to use `conda-forge` as much as we can. Hence this PR suggests installing the auto api generation package from `conda-forge` instead of `PyPI`. 
Please feel free to check the rendered doc section to see the new change!
> refactor: instruct user to download auto-api generation package from `conda-forge` instead of `PyPI`

- doc/source/tutorials/level-1-2-3-tutorials.rst
- news/private-vs-public.rst
closes #462 
Instead of having a description of private vs public functions in the paper, this has been moved to level 2 of the docs with a simple example.
> docs: add description of public vs private functions to level 2

- .gitignore
- news/build-ignore.rst
- {{ cookiecutter.github_repo_name }}/.gitignore
when using `sphinx-reload` to dynamically edit docs, it generates the directory `_build`. Adding this to the gitignore makes sure we dont accidentally commit these docs
> chore: add `_build` to `.gitignore`

- doc/source/snippets/github-codecov-setup.rst
- doc/source/support/frequently-asked-questions.rst
- doc/source/tutorials/tutorial-level-5-migration.rst
- doc/source/tutorials/tutorial-level-5.rst
- news/codecov-org.rst
Closes #490 
Finally, we are able to set all our CIs  (`PYPI_TOKEN`, `PAT_TOKEN`, and `CODECOV_TOKEN` `PRE_COMMIT CI`) all at the org level. 
Here is a quick test CI using my `bobleesj-test-org` repo: https://github.com/bobleesj-test-org/bobleesj.release/pull/30
Org secret:
Please review the new instruction I've provided with a screenshot:
> ci: allow setting global `CODECOV_TOKEN` at the org level instead of manually setting different one for each repo 

- doc/source/release-guides/conda-forge.rst
- doc/source/release-guides/pypi-github.rst
- doc/source/snippets/conda-env-setup-simple.rst
- doc/source/snippets/doc-local-build.rst
- doc/source/snippets/github-upload-all-remaining-files-level-4.rst
- doc/source/snippets/github-upload-all-remaining-files-level-5.rst
- doc/source/snippets/github-upload-readme-pre-commit.rst
- doc/source/snippets/github-workflow-moving-forward.rst
- doc/source/snippets/news-file-format.rst
- doc/source/snippets/package-install-test-local.rst
- doc/source/snippets/pre-commit-local-setup.rst
- doc/source/snippets/scikit-installation.rst
- doc/source/support/frequently-asked-questions.rst
- doc/source/tutorials/tutorial-level-1-2-3.rst
- doc/source/tutorials/tutorial-level-4-to-5.rst
- doc/source/tutorials/tutorial-level-4.rst
- doc/source/tutorials/tutorial-level-5-migration.rst
- doc/source/tutorials/tutorial-level-5.rst
- news/rm-dollar-sign.rst
closes #529 
This might give us some merge conflicts between this and the other PR: https://github.com/scikit-package/scikit-package/pull/526 but this should be nbd since its a small fix. 
edit: I added back the `$` for migration docs. This might help with the merge conflict but still might get some issues still.
> docs: remove `$` from codeblocks

- doc/source/tutorials/tutorial-level-5-migration.rst
- news/migration-docs-edits.rst
As per the convo we had during the hackathon, I found a decent middle-ground for running pre-commit with the `scikit-package` config files. See screenshot for these steps. running `git add -- . '!:<package-name>'` is a quick way that adds all the edits made by pre-commit and excludes the package created by `package create public`. I think this keeps things simple for the users and runs pre-commit early in the workflow. This works for packages that have already been cut in the past and packages that have never be cut at all. 
Additionally, I made some other changes that are more clear for beginner users.
closes #528
> docs: optimize and simplify migration docs and fix typos

- doc/source/support/frequently-asked-questions.rst
- news/doc-build-api-doc.rst
Closes #https://github.com/scikit-package/scikit-package/issues/539
Tis PR updates the existing API doc building instruction for namespace package:
Here is the current updated version:
Please read the streamlined instruction! It's one of my favorite features. 
-->
> Include package build api-doc instruction for namespace import.

- doc/source/release-guides/conda-forge.rst
- news/fix-typo.rst
Just a quick typo caught by @ycexiao in https://github.com/scikit-package/scikit-package/pull/541
> chore: fix minor typo in `package create conda-forge` doc

- docs/source/index.rst
- docs/source/snippets/user-input-manuscript.rst
- docs/source/tutorials/tutorial-level-4.rst
- docs/source/tutorials/tutorial-manuscript.rst
- docs/source/tutorials/tutorial-scikit-package-manuscript.rst
- news/skm-doc.rst
Closes #517 
Add a `package create manuscript`  section in the documentation.
Please check the rendered documentation.
> docs: add documentation for `package create manuscript`

- news/mock-add-news.rst
- tests/test_add_news.py
@sbillinge since we've added `pytest-mocker`, maybe it's a good practice to utilize mocker?
Please see my in-line comments
> Use pytest-mocker to override paths instead of manually overriding the paths for package add news function.

- news/subcommand-help.rst
- src/scikit_package/scikit_package_app.py
Closes #589. Display help message for `package create <subcommand> -h`.
Please see the inputs/outputs.
```
❯ package create manuscript -h                                                   
usage: package create manuscript [-h]
options:
-h, --help  show this help message and exit
Create Overleaf LaTeX template of Billinge group.
```
Other `package create <subcommand> -h` is also enabled, e.g.
```
❯ package create public -h    
usage: package create public [-h]
options:
-h, --help  show this help message and exit
Create a public package
```
Also, do we want to change the current help message for `package create manuscript -h`? Like "Create a LaTeX manuscript project", since now we want to recommend it to users outside the Billing group, and it is now less related to Overleaf.
> feat: let `package create <subcommand> -h` display help text

- README.rst
- news/fix-pypi-img.rst
Closes #594.
The image rendering issue occurs because the images are referenced using relative paths within the project. The fix uses `https://raw.githubusercontent.com/`, allowing `README.rst` to resolve all images independently.
Please check the modifications.
> docs: fix ``README.rst`` image rendering in PyPI

- news/revert-news.rst
- tests/test_add_news.py
Revert #608 since we decided to add `news` into the source list https://github.com/conda-forge/scikit-package-feedstock/pull/6/commits/fffbe2263fa7625939a0aeab3dc2e9583d07c145.
> chore: revert the change as `news` is added in the source list

- docs/source/snippets/user-input-level-5.rst
- news/doc-multiple-authors.rst
Closes #616
Add description for multiple authors and multiple maintainers in `user-input-level-5.rst`
Please see the modified rendered documentation.
> doc: add descriptions for multiple authors and multiple maintainers

- hooks/post_gen_project.py
- news/rm-example-files.rst
Closes #619
`scikit-package-logo-text.png` and `example-table.rst` will also be removed when running `package update`.
Please see if it is the expected behavior.
Input:
Doesn't change.
Output:
Here is an example output run in a project `agents_for_diffpy`. This project didn't have `scikit-package-logo-text.png` and `example-table.rst` previously, and also won't have them after `package update` as shown below.
```
├── docs
│   ├── make.bat
│   ├── Makefile
│   └── source
│       ├── api
│       │   └── agents_for_diffpy.rst
│       ├── conf.py
│       ├── img
│       ├── index.rst
│       ├── license.rst
│       ├── release.rst
│       ├── snippets
│       └── _static
```
> chore: add additional example files to be removed when running `package update`
